
project_id = "vtaufnxworztolfdwlll"

[functions.n8n-proxy]
verify_jwt = false

[functions.file-analysis]
verify_jwt = false

[functions.file-analysis-config]
verify_jwt = false

[functions.image-analysis]
verify_jwt = false

[functions.report-progress]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.n8n-webhook-proxy]
verify_jwt = false

[functions.send-signup-invite]
verify_jwt = false
